
server:
  port: '9093'
spring:
  application:
    name: location-service
  datasource:
    password: 123
    url: jdbc:postgresql://localhost:5432/MyDB
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL82Dialect
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: 'true'
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
